title: Bowen Yang
first_name: Bowen
middle_name:
last_name: Yang
contact_note: >
  You can reach me via email or GitHub.
description: >
  Academic personal website, showcasing publications, projects, and news.
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> 
  with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
  Photos from <a href="https://unsplash.com" target="_blank">Unsplash</a>.
keywords: academic, publications, projects, portfolio
lang: en
icon: ⚛️

url: https://Yangbowen666.github.io
baseurl: /Rye
last_updated: true
impressum_path:
back_to_top: true

author:
  name: Bowen Yang
  email: your_email@example.com
  github: Yangbowen666
  scholar: abc123
  twitter: your_twitter_username

# 避免 download-3rd-party.rb 插件报错
third_party_libraries: {}
